title: Mbida Fabrice Data Science and ML Portfolio
description: A portfolio to showcase my DS/ML projects. Contact me if interested
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
include: ['**/*.py']
